Commented "from networkx.utils import accumulate"
Since it fails:

``` 
Traceback (most recent call last):
File "salience.py", line 17, in <module>
    from networkx.utils import accumulate
ImportError: cannot import name 'accumulate' from 'networkx.utils' 
```