Update salience.py
Solves:
```
    T[path[i]][path[i+1]]=1 #updating the matrix T because there is a link
     IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```